!--------------------------------------------------
!- 27 October 2019 08:42:22
!- Import of : HANG.PRG
!- From Disk : c:\users\marka\games\c64\cbmprg\cassette50reboot\hangman.d64
!- Commodore 64
!--------------------------------------------------
1 PRINT"{clear}{white}{space*2}{down*8}{right*13}hangman":PRINT"{white}{space*15}{cm y*7}":PRINT"{green}{space*6}cascade (c) 1984{space*3}{yellow}1{orange}9{green}8{yellow}4":PRINT"{down*2}{light blue}{space*6}do you need instructions ?":PRINT"{space*3}(reply y for {cyan}'yes'{light blue} or n for {cyan}'no'{light blue})
12 GETX$:IFX$=""THEN12
13 IFX$="n"THEN50
20 PRINT"{clear}always reply y for yes,or n for no.":PRINT"i will print:{down}":PRINT"{space*11}unknown word=----":PRINT"each - stands for a missing letter.":PRINT:PRINT"when i print '{reverse on}press any letter{reverse off}',":PRINT"follow the instruction !{down}
27 PRINT"if a letter is in the unknown word":PRINT"more than once you will need to press":PRINT"the letter more than once.{down}":PRINT"e.g.'apple'has 2 p's,press p once and":PRINT"i reply:{space*4}unknown word=-p---{down}":PRINT"press p a second time and i reply
33 PRINT"{space*12}unknown word=-pp--":PRINT:PRINT"you have to complete the word before":PRINT"i hang the man.":PRINT"{reverse on}press any key when ready{reverse off}
40 GETX$:IFX$=""THEN40
50 PRINT"{clear}"TAB(16)"hangman":PRINTTAB(16)"{cm t*7}{home}";:RA=INT(RND(1)*197+1):IFA$="end"THEN340
110 FORI=1TORA:READA$:IFA$="end"THEN340
130 NEXTI:RESTORE:LA=LEN(A$):Z$=CHR$(18)+A$:D$="":FORI=1TOLA:D$=D$+"- ":NEXTI:PRINT"{down}":PRINTTAB(2)"unknown word = "D$"{home}";:N=0:L=0
210 PRINT"{down*4}{space*7}{reverse on}press any letter{reverse off}{space*2}{home}";
220 GETL$:IFL$=""THEN220
221 IFL$<>" "THEN300
230 PRINT"{down*4}{space*6}is not a letter{space*9}":GOSUB9200:PRINT"{up}{space*35}{home}";:GOTO210
300 GOSUB1000:IFN<LATHEN210
314 IFN=(LA+1)THENT1=TI:GOTO317
315 PRINT"{down*4}{yellow}{space*6}you win!!{light blue}{space*8}":T1=TI
317 IF(TI-T1)<200THEN317
320 PRINT"{clear} do you want another go?
330 GETB$:IFB$=""THEN330
331 IFB$="y"THEN50
340 PRINT"{clear} thank-you for playing":STOP
1000 LF=0:FORI=1TOLA:B$=MID$(A$,I,1):IFB$<>L$THEN1060
1033 PRINT"{down*4}{space*7}letter in word{space*4}{home}";:N=N+1:GOSUB9200:IA=15+(I*2):PRINT"{down}":PRINTTAB(IA)L$"{home}";:II=I:GOSUB8000:LF=LF+1:RETURN
1060 NEXTI:IFLF=0THENGOSUB2000
1080 RETURN
2000 L=L+1:PRINT"{down*4}{space*7}letter not in word{home}":GOSUB9200:ONLGOSUB3000,3500,4000,4500,5000,5500,6000,6500,7000:IFL<10THENRETURN
2100 K=21:GOSUB9000:PRINTTAB(19)"{cm d}{reverse on}{cm v}{reverse off}{cm k}{reverse on}{cm k}{cm c}{reverse off}{cm f}{home}";:PRINT"{down}":X$=Z$+"{reverse off}{space*11}":PRINTTAB(16)X$:PRINT"{down}{space*7}sorry,you lost{space*4}{home}";:N=LA+1:RETURN
3000 K=23:GOSUB9000:PRINT"{cm @*30}{home}";:RETURN
3500 K=6:GOSUB9000:FORI=1TO18:PRINTTAB(12)"{black}{cm +}{light blue}":NEXTI:PRINT"{home}";:RETURN
4000 K=6:GOSUB9000:PRINTTAB(13)"{black}{cm +*10}{light blue}{home}";:RETURN
4500 K=11:GOSUB9000:PRINTTAB(13)"{sh pound}{left}{up}{reverse on}{sh pound}{reverse off}{sh pound}{left}{up}{reverse on}{sh pound}{reverse off}{sh pound}{left}{up}{reverse on}{sh pound}{reverse off}{sh pound}{left}{up}{reverse on}{sh pound}{reverse off}{sh pound}{home}";:RETURN
5000 K=7:GOSUB9000:PRINTTAB(22)"{cm g}{home}";:RETURN
5500 K=8:GOSUB9000:PRINTTAB(20)"{reverse on}{sh pound}{space*2}{cm asterisk}":PRINTTAB(19)"U{sh pound}WW{cm asterisk}I":PRINTTAB(19)"J{cm g} {cm g}{cm m}K":PRINTTAB(20)"MUIN":PRINTTAB(21)"{cm t*2}{home}";:RETURN
6000 K=12:GOSUB9000:PRINTTAB(19)"N{cm t*4}M":PRINTTAB(18)"{cm m*2}^ ^ {cm g*2}":PRINTTAB(18)"{cm m*2} ^{space*2}{cm g*2}":PRINTTAB(18)"{cm m}{sh @}{space*3}^L{cm g}":PRINTTAB(20)"L{cm @*2}{sh @}{home}";:RETURN
6500 K=16:GOSUB9000:PRINTTAB(19)"#L{cm @*2}{sh @}#{home}";:RETURN
7000 K=17:GOSUB9000:FORI=1TO4:PRINTTAB(20)"{reverse on}{cm g}{cm m}{cm g}{cm m}":NEXTI:PRINT"{home}";:RETURN
8000 X=II-1:Y=LA-II:IFX=0ANDY=0THEN8500
8020 IFX=0THENA$=" "+RIGHT$(A$,Y):RETURN
8030 IFY=0THENA$=LEFT$(A$,X)+" ":RETURN
8040 A$=LEFT$(A$,X)+" "+RIGHT$(A$,Y):RETURN
8500 A$="":FORI=1TOLA:A$=A$+" ":NEXTI:RETURN
9000 FORI=2TOK:PRINT"{down}";:NEXTI:RETURN
9200 T=TI
9210 IF(TI-T)<100THEN9210
9220 RETURN
9500 DATA ABSENCE,ACCEPT,ACCIDENTALLY, ACCOMMODATE,ACHIEVED,ACKNOWLEDGE, ACQUAINTED,ADDRESSES,AERIAL,AGGRAVATE,AGREEABLE,AMATEUR,AMONG, ANTARCTIC,ANXIETY,APPARENT,APPEARANCE,APPROPRIATE,ARCTIC,ARGUMENT,ARRANGEMENTS
9506 DATA ASCENT,ATHLETIC,AWFUL,BACHELOR, BEGINNING,BELIEVED,BENEFITED,BREATHE, BRITAIN,BUSINESS,CAPTAIN,CEILING, CEMETERY,CERTAIN,CHOICE,CLOTHES, COLLEGE,COMING,COMMITTEE,COMPARATIVE, COMPETENT,COMPLETELY,CONSCIENTIOUS
9512 DATA CONSCIOUS,CONSISTENT,CONVENIENCE, COPIES,COURSE,COURTEOUS,COURTESY, CRITICISM,DECEIVE,DECISION,DEFINITE, DESIRABLE,DESPERATE,DISAPPEARED, DISAPPOINTED,DISASTROUS,DISCIPLINE, DISSATISFIED,EFFICIENCY,EIGHTH
9518 DATA ELIMINATED,EMBARRASSED,EMPHASIZE, ENTHUSIASM,EQUIPPED,ESPECIALLY, ESSENTIAL,EXAGGERATED,EXCELLENT, EXERCISE,EXHAUSTED,EXISTENCE, EXPENSE,EXPERIENCE,FAMILIAR, FEBRUARY,FINANCIAL,FOREIGN, FORMERLY,FORTY,FRIEND,GAUGE
9525 DATA GENIUS,GOVERNMENT,GRAMMAR, GRAMOPHONE,GRIEVANCE,GUARD, GUARDIAN,HANDKERCHIEF,HEIGHT, HEROES,HONORARY,HUMOROUS,HUNGRY, HURRIEDLY,HYPOCRISY,IMAGINATION, IMMEDIATELY,IMMIGRATE,INCIDENTALLY, INDEPENDENT,INDISPENSABLE
9532 DATA INFLUENTIAL,INTELLIGENCE, IRRESISTIBLE,KNOWLEDGE,LIGHTENING, LITERATURE,LIVELIHOOD,LOSE, LOSING,LYING,MAINTENANCE, MARRIAGE,MEANT,MEDICINE, MEDITERRANEAN,MINIATURE, MINUTES,MISCHIEVOUS,MURMUR
9539 DATA NECESSARY,NIECE,NOTICEABLE, OCCASIONAL,OCCURRED,OCCURRENCE, OMITTED,OPINION,OPPORTUNITY, ORIGINALLY,PARALLEL,PARLIAMENT, PASTIME,PERMANENT,PERMISSIBLE, PERSEVERANCE,PHYSICAL,PLANNING, PLEASANT,POSSESSES,PRECEDING
9546 DATA PREFERENCE,PREJUDICE,PRIVILEGE, PROCEDURE,PROCEEDS,PROFESSIONAL, PROFESSCR,PRONUNCIATION, PROPRIETARY,PSYCHOLOGY,QUIET, REALLY,RECEIVED,RECOGNIZED, RECOMMENDED,REFERRED,RELIEVED, REPETITION,RESTAURANT,RHYTHM
9553 DATA SCARCELY,SECRETARIES,SEIZE, SENTENCE,SEPARATE,SERGEANT, SEVERELY,SHINING,SIEGE,SIMILAR, SINCERELY,SPEECH,STRENGTH, SUCCESSFUL,SUPERSEDE, SUPPRESSION,SURPRISING,SYNONYM, TENDENCY,TRAGEDY,TRANSFERRED
9560 DATA TWELFTH,UNCONSCIOUS, UNNECESSARY,UNTIL,USUALLY, VALUABLE,VIEW,WEDNESDAY, WOOLLEN, END:END
